version: 1.0.{build}
image: Visual Studio 2017
install:
- appveyor DownloadFile https://download.microsoft.com/download/8/F/9/8F9659B9-E628-4D1A-B6BF-C3004C8C954B/dotnet-1.1.1-sdk-win-x64.exe
- dotnet-1.1.1-sdk-win-x64.exe /quiet

- cmd: >-

    dnvm upgrade -r clr

    dnu restore
environment:
 PATH: $(PATH);$(PROGRAMFILES)\dotnet\

build_script:
- appveyor-retry dotnet restore -v Minimal
- dotnet build


build:
  verbosity: minimal